Revert "SimpleElastix @ master (needs newer cmake -> ubuntu:18.04):" (leads to other compilation errors):
like:

In file included from /SimpleElastix/Examples/ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx:21:0:
/opt/SimpleElastix/include/SimpleITK-1.2/SimpleITK.h:86:10: fatal error: sitkElastixImageFilter.h: No such file or directory
 #include "sitkElastixImageFilter.h"

This reverts commit b4853ab4df48670be3e7c146cd4f160760d928cf.