convert test images from greyscale to RGB:
https://stackoverflow.com/questions/34305379/how-to-convert-gray-scale-png-image-to-rgb-from-comand-line-using-image-magic$

for i in *.png ; do convert $i -define png:color-type=2  ${i%_g8b.png}_rgb.png ; done  # using mogrify does not lead to RGB images!
for i in *.png ; do convert -channel G $i -combine ${i%.png}_RGB.png ; mv -f ${i%.png}_RGB.png $i ;  done  # leads to different metric values due to missing channel

identify 2016_12_02_0101_s00_01_g8b.png
2016_12_02_0101_s00_01_g8b.png PNG 800x800 800x800+0+0 8-bit Gray 256c 351590B 0.000u 0:00.000

identify 2016_12_02_0101_s00_01_rgb.png
2016_12_02_0101_s00_01_rgb.png PNG 800x800 800x800+0+0 8-bit sRGB 536661B 0.000u 0:00.010

tests with rgb then fail with:

  2.9% (1/35) 2016_12_02_0101_s00_01.png reg/2016_12_02_0101_s00_01.tif plain copy
  5.7% (2/35) reg/2016_12_02_0101_s00_01.tif 2016_12_02_0101_s00_02.png
Traceback (most recent call last):
  File "/elastix_scripts/recRegStack.py", line 271, in <module>
    main()
  File "/elastix_scripts/recRegStack.py", line 97, in main
    register(FNs[start:], FNo, args, FNp) # skip upto start
  File "/elastix_scripts/recRegStack.py", line 214, in register
    selx.SetFixedMask(fI != 0)
  File "/opt/SimpleElastix/lib/python/SimpleITK/SimpleITK.py", line 4489, in __ne__
    return NotEqual( self, float(other) )
  File "/opt/SimpleElastix/lib/python/SimpleITK/SimpleITK.py", line 54125, in NotEqual
    return _SimpleITK.NotEqual(*args)
RuntimeError: Exception thrown in SimpleITK NotEqual: /SimpleElastix/Code/Common/include/sitkMemberFunctionFactory.hxx:209:
sitk::ERROR: Pixel type: vector of 8-bit unsigned integer is not supported in 2D byN3itk6simple19NotEqualImageFilterE