setuptools needed to avoid:
Traceback (most recent call last):
  File "/elastix_scripts/recRegStack.py", line 9, in <module>
    import itk
  File "/usr/local/lib/python3.6/dist-packages/itk/__init__.py", line 20, in <module>
    import itkBase
  File "/usr/local/lib/python3.6/dist-packages/itkBase.py", line 23, in <module>
    import pkg_resources
ModuleNotFoundError: No module named pkg_resources

https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources#10538412