ubuntu:18.04 because ubuntu:latest (20.04) has gcc which the used VNL does not know:
avoids:
In file included from /selx_build/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_iostream.h:5,
                 from /selx_build/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_deprecated.cxx:4:
/selx_build/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_compiler.h:101:4: error: #error "Dunno about this gcc"
  101 | #  error "Dunno about this gcc"
      |    ^~~~~